### ISSUE TITLE
Is this wrapper still functional?

### ISSUE THREAD

**Issue by maebli** [abertschi/postcard_creator_wrapper#39]
I was able to authenticate once, never again. Tried different Python versions, all within the specs. Not sure, any one using this wrapper successfully atm?

**Comment by wp99cp** [comment]
- What type of login do you use (SwissID or a Post account)? **Attention**, the login via SwissID only works if two-factor authentication is switched off because SwissID does not offer app passwords!

- Can you log in via the app? If the Post has changed its AGBs (which has happened recently), you will have to accept them via the APP before you can use the wrapper.

Otherwise, can you give us a more specific error message?

**Comment by abertschi** [comment]
Please post tracing output of your code.

How to increase logging output is shown [here](https://github.com/abertschi/postcards/blob/06814ae24bd3067a1318af7359eff7867df46029/postcards/postcards.py#L354) (Be aware, higher verbosity may print passwords) and mentioned [here](https://github.com/abertschi/postcard_creator_wrapper#logging).

The legacy authentication method with a post account username and password seems to finally be discontinued.
However, I can verify that an account linked with swissid and without 2 factor authentication still works. Just tested it.

**Comment by maebli** [comment]
I tried again today and it worked, sorry I don't have my error trace saved. Maybe I made too many requests. Thank you for clearing things up
